"""Dependency-free browser UI served by Trinity's HTTP bridge."""


def render_web_ui(auth_enabled=False):
    """Render chat and administrator settings for the browser client."""
    auth_controls = (
        '<input id="username" placeholder="Benutzername">'
        '<input id="password" type="password" placeholder="Passwort">'
        '<button class="secondary" id="login">Anmelden</button>'
    ) if auth_enabled else (
        '<input id="token" type="password" placeholder="Bearer Token">'
        '<button class="secondary" id="saveToken">Token speichern</button>'
    )
    page = r"""<!doctype html>
<html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Trinity Web</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0c1017;color:#edf3fb;font:15px system-ui,sans-serif}header{position:sticky;top:0;z-index:3;display:flex;gap:10px;align-items:center;padding:13px 18px;background:#121923;border-bottom:1px solid #263448}h1{margin:0;font-size:19px}.status{color:#8aa0bc;font-size:13px;margin-right:auto}button,input,textarea,select{font:inherit}button{border:0;border-radius:10px;padding:9px 13px;background:#168cf4;color:white;cursor:pointer}button.secondary{background:#263448}button[disabled]{opacity:.55;cursor:not-allowed}input,textarea,select{width:100%;background:#111923;color:#edf3fb;border:1px solid #31425a;border-radius:10px;padding:10px}#token{width:180px}.layout{max-width:1180px;margin:auto;padding:22px}.composer{display:grid;grid-template-columns:1fr auto;gap:10px;margin-bottom:18px}.composer textarea{min-height:86px;resize:vertical}.actions{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.actions input{max-width:260px}.event{margin:12px 0;padding:14px 16px;border-radius:14px;background:#141d29;border:1px solid #243247}.event.user{margin-left:12%;background:#10335b}.event .meta{font-size:12px;color:#87a0c0;margin-bottom:7px}.event .text{white-space:pre-wrap;line-height:1.45}.event img,.event video{max-width:100%;max-height:560px;border-radius:10px;margin-top:12px}.event audio{width:100%;margin-top:12px}.attachment{margin-top:8px;color:#8bd1ff;font-size:13px}.empty{color:#89a0b9;text-align:center;padding:60px}.payload{margin-top:12px;border-radius:10px;overflow:auto;background:#0b1119}.payload iframe{display:block;width:100%;height:480px;border:0;background:white}.hidden{display:none!important}.settings-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:16px}.settings-card{padding:16px;border:1px solid #263448;border-radius:14px;background:#141d29}.settings-card h2{font-size:16px;margin:0 0 12px}.field{margin:11px 0}.field label{display:block;color:#b9c9dc;font-size:13px;margin:0 0 5px}.field textarea{min-height:82px;resize:vertical}.checkbox{display:flex;gap:9px;align-items:center}.checkbox input{width:auto}.settings-note{color:#9fb2c8;line-height:1.45;margin:0 0 16px}.settings-actions{position:sticky;bottom:0;display:flex;gap:10px;justify-content:flex-end;padding:14px 0;background:#0c1017}.notice{min-height:22px;color:#8bd1ff}.danger-note{color:#f3bd6b;font-size:13px;line-height:1.45}@media(max-width:720px){header{flex-wrap:wrap}.layout{padding:12px}.event.user{margin-left:0}.composer{grid-template-columns:1fr}#token{width:100%}}
</style></head><body><header><h1>Trinity Web</h1><span class="status" id="status">Verbinde...</span><button class="secondary" id="chatView">Chat</button><button class="secondary" id="settingsView">Einstellungen</button>__AUTH_CONTROLS__</header>
<main id="chatPage" class="layout"><section class="composer"><textarea id="prompt" placeholder="Schreibe Trinity eine Nachricht oder ziehe eine Datei in die Auswahl..."></textarea><div class="actions"><input id="files" type="file" multiple accept=".txt,.md,.markdown,.csv,.tsv,.json,.yaml,.yml,.log,.py,.js,.html,.css,.pdf,.png,.jpg,.jpeg,.webp,.gif,.xlsx,.xlsm"><button id="send">Senden</button></div></section><section id="events"><div class="empty">Noch keine Nachrichten.</div></section></main>
<main id="settingsPage" class="layout hidden"><p class="settings-note">Diese Seite entspricht den zentralen Einstellungen der ClassicUI. LLM-, Persona-, Sprach- und Agentenwerte wirken bei der nächsten Anfrage; Oberflächen, Bridge und Serverzugang brauchen danach einen Neustart.</p><p class="danger-note">Sensible Schlüssel werden nur über eine lokale Verbindung, einen Bearer-Token oder ein Administrator-Konto angezeigt. Projekt-Aliasse begrenzen Codex und OpenCode auf genau diese Ordner.</p><div id="settingsNotice" class="notice"></div><section id="settingsForm" class="settings-grid"></section><section class="settings-actions"><button class="secondary" id="discardSettings">Verwerfen</button><button id="saveSettings">Einstellungen speichern</button></section></main>
<script>
const authEnabled=__AUTH_ENABLED__;
const state={after:0,token:localStorage.getItem('trinity.web.token')||'',config:null,files:{soul:'',user:''}};
const token=document.querySelector('#token');if(token)token.value=state.token;
const status=document.querySelector('#status'),events=document.querySelector('#events'),prompt=document.querySelector('#prompt'),files=document.querySelector('#files');
const chatPage=document.querySelector('#chatPage'),settingsPage=document.querySelector('#settingsPage'),settingsForm=document.querySelector('#settingsForm'),settingsNotice=document.querySelector('#settingsNotice');
function headers(){return state.token?{'Authorization':'Bearer '+state.token,'Content-Type':'application/json'}:{'Content-Type':'application/json'}}
function escapeHtml(value){const d=document.createElement('div');d.textContent=value||'';return d.innerHTML}
function media(event){let html='';for(const item of(event.attachments||[])){const url=item.media_url||'';const mime=item.mime||'';if(url&&mime.startsWith('image/'))html+=`<img src="${url}">`;else if(url&&mime.startsWith('audio/'))html+=`<audio controls src="${url}"></audio>`;else if(url&&mime.startsWith('video/'))html+=`<video controls src="${url}"></video>`;else html+=`<div class="attachment">Anlage: ${escapeHtml(item.name||'Datei')}</div>`}if(event.payload_html)html+=`<div class="payload"><iframe sandbox="allow-scripts allow-same-origin" srcdoc="${escapeHtml(event.payload_html)}"></iframe></div>`;return html}
function render(list){if(!list.length)return;events.innerHTML=list.map(event=>`<article class="event ${event.role==='user'?'user':''}"><div class="meta">${event.role==='user'?'Du':'Trinity'} · ${new Date((event.timestamp||0)*1000).toLocaleTimeString()}</div><div class="text">${escapeHtml(event.text||'')}</div>${media(event)}</article>`).join('');window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
async function poll(){try{const response=await fetch('/events?after='+state.after,{headers:state.token?{'Authorization':'Bearer '+state.token}:{}});if(!response.ok)throw new Error(response.status);const data=await response.json();const list=data.events||[];if(list.length){state.after=Math.max(...list.map(item=>item.timestamp||0));render(list)}status.textContent='Verbunden'}catch(error){status.textContent='Verbindung oder Token pruefen'}setTimeout(poll,1200)}
async function encode(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,mime:file.type||'application/octet-stream',data_base64:String(reader.result).split(',')[1]||''});reader.onerror=reject;reader.readAsDataURL(file)})}
function pathValue(object,path,fallback=''){return path.split('.').reduce((value,key)=>value&&value[key]!==undefined?value[key]:undefined,object)??fallback}
function setPath(object,path,value){const keys=path.split('.');let target=object;for(const key of keys.slice(0,-1)){target[key]=target[key]&&typeof target[key]==='object'?target[key]:{};target=target[key]}target[keys[keys.length-1]]=value}
function clone(value){return JSON.parse(JSON.stringify(value||{}))}
function projectsText(value){return Object.entries(value||{}).map(([name,path])=>`${name} = ${path}`).join('\n')}
function parseProjects(value){const projects={};String(value||'').split('\n').forEach(line=>{const index=line.indexOf('=');if(index>0){const name=line.slice(0,index).trim(),path=line.slice(index+1).trim();if(name&&path)projects[name]=path}});return projects}
const sections=[
 {title:'Persona',fields:[['persona.agent_name','Name von Trinity','text'],['persona.trigger_variants','Wakeword-Varianten (kommagetrennt)','text','list']]},
 {title:'LLM',fields:[['llm.active_slot','Aktiver Slot','select',['local','remote_1','remote_2']],['llm.local.url','Lokale URL','text'],['llm.local.model','Lokales Modell','text'],['llm.local.api_key','Lokaler API-Schlüssel','password'],['llm.remote_1.url','Remote 1 URL','text'],['llm.remote_1.model','Remote 1 Modell','text'],['llm.remote_1.api_key','Remote 1 API-Schlüssel','password'],['llm.remote_2.url','Remote 2 URL','text'],['llm.remote_2.model','Remote 2 Modell','text'],['llm.remote_2.api_key','Remote 2 API-Schlüssel','password']]},
 {title:'Sprache und Audio',fields:[['stt.model','STT-Modell','select',['tiny','base','small','medium','large']],['stt.silence_threshold','Stille-Schwelle','number'],['stt.chunk_duration','Chunk-Dauer (Sekunden)','number'],['stt.show_volume_meter','Pegelanzeige','checkbox'],['tts.voice','Desktop-TTS-Stimme','text'],['audio_routing.private_device','Privates Audiogeraet','text'],['audio_routing.public_device','Oeffentliches Audiogeraet','text']]},
 {title:'Proaktiv und Oberflaechen',fields:[['proactive.heartbeat_enabled','Heartbeat aktiv','checkbox'],['proactive.bubbles_enabled','Bubbles aktiv','checkbox'],['proactive.visuals_enabled','Visuelle Hinweise aktiv','checkbox'],['proactive.interval_minutes','Heartbeat-Intervall (Minuten)','number'],['system.mode','Modus','select',['office','lecture','chat']],['system.eyes_ui_enabled','Augen-UI','checkbox'],['system.classic_ui_enabled','ClassicUI','checkbox'],['system.web_ui_enabled','WebUI','checkbox'],['system.terminal_cli_enabled','Terminal-CLI','checkbox'],['system.show_terminal','Terminalfenster anzeigen','checkbox'],['system.windows_speech_enabled','Windows-Spracheingabe','checkbox']]},
 {title:'APIs und Bild',fields:[['apis.tavily','Tavily API-Schlüssel','password'],['apis.fal_ai','fal.ai API-Schlüssel','password'],['image.primary_model','Primäres Bildmodell','text'],['image.fallback_model','Fallback-Bildmodell','text'],['comfyui.enabled','ComfyUI aktiv','checkbox'],['comfyui.server_url','ComfyUI-Server','text'],['comfyui.default_workflow','ComfyUI-Workflow','text']]},
 {title:'Codex',fields:[['codex.enabled','Codex-Auftraege erlauben','checkbox'],['codex.executable','Programm','text'],['codex.projects','Freigegebene Projekte: Alias = Pfad','textarea','projects'],['codex.default_project','Standardprojekt','text'],['codex.sandbox','Sandbox','select',['read-only','workspace-write']],['codex.timeout_seconds','Zeitlimit (Sekunden)','number'],['codex.max_output_chars','Antwortlaenge','number'],['codex.ephemeral','Keine dauerhafte Codex-Sitzung','checkbox'],['codex.network_access','Netzwerkzugriff fuer Codex','checkbox']]},
 {title:'OpenCode',fields:[['opencode.enabled','OpenCode-Auftraege erlauben','checkbox'],['opencode.executable','Programm','text'],['opencode.projects','Freigegebene Projekte: Alias = Pfad','textarea','projects'],['opencode.default_project','Standardprojekt','text'],['opencode.agent','OpenCode-Agent','text'],['opencode.model','Modell (optional)','text'],['opencode.timeout_seconds','Zeitlimit (Sekunden)','number'],['opencode.max_output_chars','Antwortlaenge','number']]},
 {title:'Telegram, Companion, Server und Profil',fields:[['telegram.enabled','Telegram aktiv','checkbox'],['telegram.bot_token','Telegram Bot-Token','password'],['telegram.chat_id','Telegram Chat-ID','text'],['companion.enabled','Companion Bridge aktiv','checkbox'],['companion.host','Bridge-Host','text'],['companion.port','Bridge-Port','number'],['companion.token','Bridge Bearer-Token','password'],['server.host','Server-Host','text'],['server.port','Server-Port','number'],['server.token','Server Bearer-Token','password'],['server.auth_enabled','Server-Accounts aktiv','checkbox'],['client.enabled','Als Remote-Client verwenden','checkbox'],['client.server_url','Remote-Server URL','text'],['client.username','Remote-Benutzername','text'],['client.token','Remote-Sitzungstoken','password'],['__file.soul','Soul.md','textarea','file'],['__file.user','User.md','textarea','file']]}
];
function inputFor(path,label,type,extra){const value=path.startsWith('__file.')?state.files[path.slice(7)]||'':pathValue(state.config,path,'');const field=document.createElement('div');field.className='field';if(type==='checkbox'){field.className='field checkbox';const input=document.createElement('input');input.type='checkbox';input.checked=Boolean(value);input.dataset.path=path;field.append(input);const caption=document.createElement('label');caption.textContent=label;caption.htmlFor=path;field.append(caption);return field}const caption=document.createElement('label');caption.textContent=label;field.append(caption);let input;if(type==='textarea'){input=document.createElement('textarea')}else if(type==='select'){input=document.createElement('select');(extra||[]).forEach(option=>{const item=document.createElement('option');item.value=option;item.textContent=option;item.selected=String(value)===option;input.append(item)})}else{input=document.createElement('input');input.type=type||'text'}input.dataset.path=path;if(extra==='projects')input.value=projectsText(value);else if(extra==='list')input.value=(value||[]).join(', ');else input.value=value??'';field.append(input);return field}
function renderSettings(){settingsForm.innerHTML='';sections.forEach(section=>{const card=document.createElement('section');card.className='settings-card';const title=document.createElement('h2');title.textContent=section.title;card.append(title);section.fields.forEach(field=>card.append(inputFor(...field)));settingsForm.append(card)})}
async function loadSettings(){settingsNotice.textContent='Lade Einstellungen...';try{const response=await fetch('/settings',{headers:state.token?{'Authorization':'Bearer '+state.token}:{}});const data=await response.json();if(!response.ok)throw new Error(data.error||response.status);state.config=data.config||{};state.files=data.files||{};renderSettings();settingsNotice.textContent='Einstellungen geladen.'}catch(error){settingsNotice.textContent='Einstellungen nicht verfuegbar: '+(error.message||error)}}
async function saveSettings(){const next=clone(state.config),nextFiles=clone(state.files);for(const input of settingsForm.querySelectorAll('[data-path]')){const path=input.dataset.path;let value=input.type==='checkbox'?input.checked:input.value;if(path.startsWith('__file.')){nextFiles[path.slice(7)]=value;continue}if(input.tagName==='TEXTAREA'&&path.endsWith('.projects'))value=parseProjects(value);else if(path==='persona.trigger_variants')value=String(value).split(',').map(item=>item.trim()).filter(Boolean);else if(input.type==='number')value=Number(value);setPath(next,path,value)}try{const response=await fetch('/settings',{method:'POST',headers:headers(),body:JSON.stringify({config:next,soul:nextFiles.soul||'',user:nextFiles.user||''})});const data=await response.json();if(!response.ok)throw new Error(data.error||response.status);state.config=data.config||next;state.files=data.files||nextFiles;settingsNotice.textContent='Gespeichert. Laufzeitwerte gelten bei der naechsten Anfrage; Oberflaechen und Bridge nach Bedarf neu starten.'}catch(error){settingsNotice.textContent='Speichern fehlgeschlagen: '+(error.message||error)}}
function showView(name){const settings=name==='settings';chatPage.classList.toggle('hidden',settings);settingsPage.classList.toggle('hidden',!settings);if(settings&&!state.config)loadSettings()}
const saveToken=document.querySelector('#saveToken');if(saveToken)saveToken.onclick=()=>{state.token=token.value.trim();localStorage.setItem('trinity.web.token',state.token);state.after=0;events.innerHTML='';state.config=null;};
const login=document.querySelector('#login');if(login){async function authStatus(){const response=await fetch('/auth/status');const data=await response.json();login.textContent=data.bootstrap_required?'Admin anlegen':'Anmelden';status.textContent=data.bootstrap_required?'Bitte ersten Admin-Account anlegen':'Anmelden';}login.onclick=async()=>{const isBootstrap=login.textContent.includes('anlegen');try{const response=await fetch(isBootstrap?'/auth/register':'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:document.querySelector('#username').value.trim(),password:document.querySelector('#password').value})});const data=await response.json();if(!response.ok)throw new Error(data.error||response.status);state.token=data.token;localStorage.setItem('trinity.web.token',state.token);document.querySelector('#password').value='';state.after=0;events.innerHTML='';state.config=null;status.textContent='Angemeldet';}catch(error){status.textContent=error.message||'Anmeldung fehlgeschlagen';}};authStatus().catch(()=>status.textContent='Serverstatus nicht erreichbar');}
document.querySelector('#send').onclick=async()=>{const text=prompt.value.trim();const attachments=await Promise.all([...files.files].map(encode));if(!text&&!attachments.length)return;try{const response=await fetch('/message',{method:'POST',headers:headers(),body:JSON.stringify({text,attachments,source:'web',speak:false})});if(!response.ok)throw new Error(await response.text());prompt.value='';files.value='';status.textContent='Auftrag gesendet'}catch(error){status.textContent='Senden fehlgeschlagen'}};
document.querySelector('#chatView').onclick=()=>showView('chat');document.querySelector('#settingsView').onclick=()=>showView('settings');document.querySelector('#discardSettings').onclick=()=>loadSettings();document.querySelector('#saveSettings').onclick=saveSettings;poll();
</script></body></html>"""
    return page.replace("__AUTH_CONTROLS__", auth_controls).replace(
        "__AUTH_ENABLED__", "true" if auth_enabled else "false"
    )
